### ISSUE TITLE
 Protocol not supported

### ISSUE THREAD

**Issue by mahdidrm** [EvelynFan/FAU#12]
Hello. 

I made a Json file of AU and coordinates. but when I run the code I got this error: 

 ```
ZMQError in socket.bind(). Perhaps you're                 using pipes on a non-local file system. See documentation of PrefetchDataZMQ for more information.
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    main()
  File "train.py", line 16, in main
    trainer = Trainer(Model_graph(), cfg)
  File "FAU\lib\base.py", line 179, in __init__
    self._data_iter, self.itr_per_epoch = self._make_data()
  File "FAU\lib\base.py", line 193, in _make_data
    data_load_thread.reset_state()
  File "FAU\lib\data_provider.py", line 371, in reset_state
    self.ds.reset_state()
  File "FAU\lib\data_provider.py", line 266, in reset_state
    self._reset_once()  # build processes
  File "FAU\lib\data_provider.py", line 236, in _reset_once
    self.socket.bind(pipename)
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Protocol not supported
MultiProcessMapDataZMQ successfully cleaned-up.
MultiProcessMapDataZMQ successfully cleaned-up.ed-up.
 ```

Note that all the addresses in config.py are correct. Can you guide me please?

Regards

**Comment by mahdidrm** [comment]
Problem solved.
At first we need to create a single Json file. I did this using OpenFace on DISFA dataset. I took the X and Y coordinates of the LandMarks associated with each Action Units, then converted them to the format mentioned on the Readme file.

Also my problem was the train and the test files. I made them using "from sklearn.model_selection import train_test_split". 

Note: we need to pay attention to the addresses in all Train, Config, and Datasets files.
